version: '3.8'

services:
  wsp-admin:
    build: 
      context: .
    command: uvicorn main:app --reload --proxy-headers --host 0.0.0.0 --port 95
    expose:
      - 95
    volumes:
      - ./app:/app/

  nginx:
    image: nginx:latest
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=wsp-admin.diego-luque.com
      - LETSENCRYPT_HOST=wsp-admin.diego-luque.com
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wsp-admin

networks:
  default:
    name: web_private_red_webapps #dbs_red_db
    external: true
