version: '3.8'

services:
  wsp-admin:
    build: 
      context: .
    # este servicio se puede usar sin nginx pero debes habilitar los puertos
    # ports:
    #   - "94:94"
    command: uvicorn main:app --reload --proxy-headers --host 0.0.0.0 --port 95
    expose:
      - 95
    volumes:
      - ./app:/app/
    environment:
      - SERVER_HOST=mysqldb_mariadb_1

  nginx:
    image: nginx:latest
    ports:
      - "1819:80"
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=wsp-admim.diego-luque.com
      - LETSENCRYPT_HOST=wsp-admin.diego-luque.com
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bot

networks:
  default:
    name: web_private_red_webapps #dbs_red_db
    external: true
